package com.android.tonight8.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXPRESS.
 */
public class Express {

    private long id;
    private Integer type;
    private Long sendId;
    private String expressCompany;
    private String expressNumber;
    private String shippingNumber;

    public Express() {
    }

    public Express(long id) {
        this.id = id;
    }

    public Express(long id, Integer type, Long sendId, String expressCompany, String expressNumber, String shippingNumber) {
        this.id = id;
        this.type = type;
        this.sendId = sendId;
        this.expressCompany = expressCompany;
        this.expressNumber = expressNumber;
        this.shippingNumber = shippingNumber;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getSendId() {
        return sendId;
    }

    public void setSendId(Long sendId) {
        this.sendId = sendId;
    }

    public String getExpressCompany() {
        return expressCompany;
    }

    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany;
    }

    public String getExpressNumber() {
        return expressNumber;
    }

    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber;
    }

    public String getShippingNumber() {
        return shippingNumber;
    }

    public void setShippingNumber(String shippingNumber) {
        this.shippingNumber = shippingNumber;
    }

}
