package com.android.tonight8.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POP_PIC.
 */
public class PopPic {

    private long id;
    private Integer type;
    private Long relateId;
    private String url;
    private String describe;

    public PopPic() {
    }

    public PopPic(long id) {
        this.id = id;
    }

    public PopPic(long id, Integer type, Long relateId, String url, String describe) {
        this.id = id;
        this.type = type;
        this.relateId = relateId;
        this.url = url;
        this.describe = describe;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getRelateId() {
        return relateId;
    }

    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

}
