package com.android.tonight8.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PPT.
 */
public class PPT {

    private long id;
    private Integer relateType;
    private Long relateId;
    private Integer frameCount;
    private Integer timeCount;

    public PPT() {
    }

    public PPT(long id) {
        this.id = id;
    }

    public PPT(long id, Integer relateType, Long relateId, Integer frameCount, Integer timeCount) {
        this.id = id;
        this.relateType = relateType;
        this.relateId = relateId;
        this.frameCount = frameCount;
        this.timeCount = timeCount;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getRelateType() {
        return relateType;
    }

    public void setRelateType(Integer relateType) {
        this.relateType = relateType;
    }

    public Long getRelateId() {
        return relateId;
    }

    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    public Integer getFrameCount() {
        return frameCount;
    }

    public void setFrameCount(Integer frameCount) {
        this.frameCount = frameCount;
    }

    public Integer getTimeCount() {
        return timeCount;
    }

    public void setTimeCount(Integer timeCount) {
        this.timeCount = timeCount;
    }

}
