package com.android.tonight8.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REGIONAL.
 */
public class Regional {

    private long id;
    private Integer level;
    private Long pid;
    private String name;
    private String code;

    public Regional() {
    }

    public Regional(long id) {
        this.id = id;
    }

    public Regional(long id, Integer level, Long pid, String name, String code) {
        this.id = id;
        this.level = level;
        this.pid = pid;
        this.name = name;
        this.code = code;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Long getPid() {
        return pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

}
