package com.android.tonight8.dao.entity;

import com.android.tonight8.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.android.tonight8.dao.EventDao;
import com.android.tonight8.dao.SubjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUBJECT.
 */
public class Subject {

    private long id;
    private Long eventId;
    private Integer publisherRole;
    private Long publisherId;
    private Boolean isCouponDispatch;
    private Boolean hasPhoto;
    private Boolean hasAudio;
    private Boolean hasSource;
    private String content;
    private String date;
    private String time;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SubjectDao myDao;

    private Event event;
    private Long event__resolvedKey;


    public Subject() {
    }

    public Subject(long id) {
        this.id = id;
    }

    public Subject(long id, Long eventId, Integer publisherRole, Long publisherId, Boolean isCouponDispatch, Boolean hasPhoto, Boolean hasAudio, Boolean hasSource, String content, String date, String time) {
        this.id = id;
        this.eventId = eventId;
        this.publisherRole = publisherRole;
        this.publisherId = publisherId;
        this.isCouponDispatch = isCouponDispatch;
        this.hasPhoto = hasPhoto;
        this.hasAudio = hasAudio;
        this.hasSource = hasSource;
        this.content = content;
        this.date = date;
        this.time = time;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSubjectDao() : null;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public Integer getPublisherRole() {
        return publisherRole;
    }

    public void setPublisherRole(Integer publisherRole) {
        this.publisherRole = publisherRole;
    }

    public Long getPublisherId() {
        return publisherId;
    }

    public void setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
    }

    public Boolean getIsCouponDispatch() {
        return isCouponDispatch;
    }

    public void setIsCouponDispatch(Boolean isCouponDispatch) {
        this.isCouponDispatch = isCouponDispatch;
    }

    public Boolean getHasPhoto() {
        return hasPhoto;
    }

    public void setHasPhoto(Boolean hasPhoto) {
        this.hasPhoto = hasPhoto;
    }

    public Boolean getHasAudio() {
        return hasAudio;
    }

    public void setHasAudio(Boolean hasAudio) {
        this.hasAudio = hasAudio;
    }

    public Boolean getHasSource() {
        return hasSource;
    }

    public void setHasSource(Boolean hasSource) {
        this.hasSource = hasSource;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    /** To-one relationship, resolved on first access. */
    public Event getEvent() {
        Long __key = this.eventId;
        if (event__resolvedKey == null || !event__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            EventDao targetDao = daoSession.getEventDao();
            Event eventNew = targetDao.load(__key);
            synchronized (this) {
                event = eventNew;
            	event__resolvedKey = __key;
            }
        }
        return event;
    }

    public void setEvent(Event event) {
        synchronized (this) {
            this.event = event;
            eventId = event == null ? null : event.getId();
            event__resolvedKey = eventId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
