package com.android.tonight8.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table THEME.
 */
public class Theme {

    private long id;
    private Integer relateType;
    private Long relateId;
    private String backgroundPic;

    public Theme() {
    }

    public Theme(long id) {
        this.id = id;
    }

    public Theme(long id, Integer relateType, Long relateId, String backgroundPic) {
        this.id = id;
        this.relateType = relateType;
        this.relateId = relateId;
        this.backgroundPic = backgroundPic;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getRelateType() {
        return relateType;
    }

    public void setRelateType(Integer relateType) {
        this.relateType = relateType;
    }

    public Long getRelateId() {
        return relateId;
    }

    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    public String getBackgroundPic() {
        return backgroundPic;
    }

    public void setBackgroundPic(String backgroundPic) {
        this.backgroundPic = backgroundPic;
    }

}
