package com.android.tonight8.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.tonight8.dao.entity.Event;
import com.android.tonight8.dao.entity.Wish;

import com.android.tonight8.dao.entity.Ready;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table READY.
*/
public class ReadyDao extends AbstractDao<Ready, Long> {

    public static final String TABLENAME = "READY";

    /**
     * Properties of entity Ready.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "ID");
        public final static Property EventId = new Property(1, Long.class, "eventId", false, "EVENT_ID");
        public final static Property WishId = new Property(2, Long.class, "wishId", false, "WISH_ID");
        public final static Property PublishTime = new Property(3, String.class, "publishTime", false, "PUBLISH_TIME");
        public final static Property DateStart = new Property(4, String.class, "dateStart", false, "DATE_START");
        public final static Property TimeStart = new Property(5, String.class, "timeStart", false, "TIME_START");
        public final static Property DateEnd = new Property(6, String.class, "dateEnd", false, "DATE_END");
        public final static Property TimeEnd = new Property(7, String.class, "timeEnd", false, "TIME_END");
    };

    private DaoSession daoSession;


    public ReadyDao(DaoConfig config) {
        super(config);
    }
    
    public ReadyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'READY' (" + //
                "'ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "'EVENT_ID' INTEGER," + // 1: eventId
                "'WISH_ID' INTEGER," + // 2: wishId
                "'PUBLISH_TIME' TEXT," + // 3: publishTime
                "'DATE_START' TEXT," + // 4: dateStart
                "'TIME_START' TEXT," + // 5: timeStart
                "'DATE_END' TEXT," + // 6: dateEnd
                "'TIME_END' TEXT);"); // 7: timeEnd
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'READY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Ready entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        Long eventId = entity.getEventId();
        if (eventId != null) {
            stmt.bindLong(2, eventId);
        }
 
        Long wishId = entity.getWishId();
        if (wishId != null) {
            stmt.bindLong(3, wishId);
        }
 
        String publishTime = entity.getPublishTime();
        if (publishTime != null) {
            stmt.bindString(4, publishTime);
        }
 
        String dateStart = entity.getDateStart();
        if (dateStart != null) {
            stmt.bindString(5, dateStart);
        }
 
        String timeStart = entity.getTimeStart();
        if (timeStart != null) {
            stmt.bindString(6, timeStart);
        }
 
        String dateEnd = entity.getDateEnd();
        if (dateEnd != null) {
            stmt.bindString(7, dateEnd);
        }
 
        String timeEnd = entity.getTimeEnd();
        if (timeEnd != null) {
            stmt.bindString(8, timeEnd);
        }
    }

    @Override
    protected void attachEntity(Ready entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Ready readEntity(Cursor cursor, int offset) {
        Ready entity = new Ready( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // eventId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // wishId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // publishTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dateStart
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // timeStart
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // dateEnd
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // timeEnd
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Ready entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setEventId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setWishId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setPublishTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDateStart(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTimeStart(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDateEnd(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTimeEnd(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Ready entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Ready entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEventDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getWishDao().getAllColumns());
            builder.append(" FROM READY T");
            builder.append(" LEFT JOIN EVENT T0 ON T.'EVENT_ID'=T0.'ID'");
            builder.append(" LEFT JOIN WISH T1 ON T.'WISH_ID'=T1.'ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Ready loadCurrentDeep(Cursor cursor, boolean lock) {
        Ready entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Event event = loadCurrentOther(daoSession.getEventDao(), cursor, offset);
        entity.setEvent(event);
        offset += daoSession.getEventDao().getAllColumns().length;

        Wish wish = loadCurrentOther(daoSession.getWishDao(), cursor, offset);
        entity.setWish(wish);

        return entity;    
    }

    public Ready loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Ready> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Ready> list = new ArrayList<Ready>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Ready> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Ready> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
