package com.android.tonight8.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.android.tonight8.dao.entity.Event;

import com.android.tonight8.dao.entity.Subject;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SUBJECT.
*/
public class SubjectDao extends AbstractDao<Subject, Long> {

    public static final String TABLENAME = "SUBJECT";

    /**
     * Properties of entity Subject.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "ID");
        public final static Property EventId = new Property(1, Long.class, "eventId", false, "EVENT_ID");
        public final static Property PublisherRole = new Property(2, Integer.class, "publisherRole", false, "PUBLISHER_ROLE");
        public final static Property PublisherId = new Property(3, Long.class, "publisherId", false, "PUBLISHER_ID");
        public final static Property IsCouponDispatch = new Property(4, Boolean.class, "isCouponDispatch", false, "IS_COUPON_DISPATCH");
        public final static Property HasPhoto = new Property(5, Boolean.class, "hasPhoto", false, "HAS_PHOTO");
        public final static Property HasAudio = new Property(6, Boolean.class, "hasAudio", false, "HAS_AUDIO");
        public final static Property HasSource = new Property(7, Boolean.class, "hasSource", false, "HAS_SOURCE");
        public final static Property Content = new Property(8, String.class, "content", false, "CONTENT");
        public final static Property Date = new Property(9, String.class, "date", false, "DATE");
        public final static Property Time = new Property(10, String.class, "time", false, "TIME");
    };

    private DaoSession daoSession;


    public SubjectDao(DaoConfig config) {
        super(config);
    }
    
    public SubjectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SUBJECT' (" + //
                "'ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "'EVENT_ID' INTEGER," + // 1: eventId
                "'PUBLISHER_ROLE' INTEGER," + // 2: publisherRole
                "'PUBLISHER_ID' INTEGER," + // 3: publisherId
                "'IS_COUPON_DISPATCH' INTEGER," + // 4: isCouponDispatch
                "'HAS_PHOTO' INTEGER," + // 5: hasPhoto
                "'HAS_AUDIO' INTEGER," + // 6: hasAudio
                "'HAS_SOURCE' INTEGER," + // 7: hasSource
                "'CONTENT' TEXT," + // 8: content
                "'DATE' TEXT," + // 9: date
                "'TIME' TEXT);"); // 10: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SUBJECT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Subject entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        Long eventId = entity.getEventId();
        if (eventId != null) {
            stmt.bindLong(2, eventId);
        }
 
        Integer publisherRole = entity.getPublisherRole();
        if (publisherRole != null) {
            stmt.bindLong(3, publisherRole);
        }
 
        Long publisherId = entity.getPublisherId();
        if (publisherId != null) {
            stmt.bindLong(4, publisherId);
        }
 
        Boolean isCouponDispatch = entity.getIsCouponDispatch();
        if (isCouponDispatch != null) {
            stmt.bindLong(5, isCouponDispatch ? 1l: 0l);
        }
 
        Boolean hasPhoto = entity.getHasPhoto();
        if (hasPhoto != null) {
            stmt.bindLong(6, hasPhoto ? 1l: 0l);
        }
 
        Boolean hasAudio = entity.getHasAudio();
        if (hasAudio != null) {
            stmt.bindLong(7, hasAudio ? 1l: 0l);
        }
 
        Boolean hasSource = entity.getHasSource();
        if (hasSource != null) {
            stmt.bindLong(8, hasSource ? 1l: 0l);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(9, content);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(10, date);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(11, time);
        }
    }

    @Override
    protected void attachEntity(Subject entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Subject readEntity(Cursor cursor, int offset) {
        Subject entity = new Subject( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // eventId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // publisherRole
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // publisherId
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isCouponDispatch
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // hasPhoto
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // hasAudio
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // hasSource
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // content
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // date
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Subject entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setEventId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setPublisherRole(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setPublisherId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIsCouponDispatch(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setHasPhoto(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setHasAudio(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setHasSource(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setContent(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Subject entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Subject entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEventDao().getAllColumns());
            builder.append(" FROM SUBJECT T");
            builder.append(" LEFT JOIN EVENT T0 ON T.'EVENT_ID'=T0.'ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Subject loadCurrentDeep(Cursor cursor, boolean lock) {
        Subject entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Event event = loadCurrentOther(daoSession.getEventDao(), cursor, offset);
        entity.setEvent(event);

        return entity;    
    }

    public Subject loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Subject> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Subject> list = new ArrayList<Subject>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Subject> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Subject> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
